# Generated by Django 2.1.2 on 2019-06-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico_secretaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secretaria',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
    ]
