# Generated by Django 2.1.2 on 2019-07-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20190707_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(choices=[('MANTENCION', 'MANTENCION'), ('REPARACION', 'REPARACION')], max_length=20)),
                ('desc_soli', models.CharField(max_length=300)),
                ('rut_cliente', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombreComp', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tecnico_encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Tecnico'),
        ),
    ]
