# Generated by Django 2.1.2 on 2019-07-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20190708_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo_contacto',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_solicitud_servicio',
            field=models.CharField(default='', max_length=80),
        ),
    ]
