# Generated by Django 2.1.2 on 2019-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20190708_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada')], default='En espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Mantencion', 'Mantencion'), ('Reparacion', 'Reparacion')], max_length=20),
        ),
    ]
