# Generated by Django 2.1.2 on 2019-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20190708_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_serv',
            field=models.DateTimeField(null=True),
        ),
    ]
