# Generated by Django 2.2.3 on 2019-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_solicitud_fecha_serv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnico',
            new_name='Medico',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='tecnico_encargado',
            new_name='medico_encargado',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='desc_soli',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='direccion_solicitud_servicio',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Enviada', 'Enviada'), ('En espera', 'En espera'), ('Finalizada', 'Finalizada')], default='Enviada', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.CharField(choices=[('Kinesiología', 'Kinesiología'), ('Oftalmología', 'Oftalmología'), ('Otorrinolaringología', 'Otorrinolaringología')], max_length=20),
        ),
    ]
