# Generated by Django 2.2.3 on 2019-07-10 03:15

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20190709_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='valor',
            field=models.IntegerField(null=True, verbose_name=hospital.models.Solicitud.valor),
        ),
    ]
