# Generated by Django 2.2.3 on 2019-07-10 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_solicitud_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='valor',
        ),
    ]
