# Generated by Django 2.2.3 on 2019-07-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_solicitud_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorTotal',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=10)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.Solicitud')),
            ],
        ),
    ]
